---

- name: Create Stack Builder AEM AWS resources stack
  hosts: all
  gather_facts: false
  connection: local

  tasks:
    - name: Create AWS resources stack
      cloudformation:
        stack_name: "{{ stack_prefix }}-{{ aws.resources.stack_name }}"
        region: "{{ aws.region }}"
        state: present
        disable_rollback: true
        template: "../../../../templates/cloudformation/apps/aws-resources.yaml"
        template_parameters:
          CreateS3Bucket: "{{ s3.create_bucket_bool }}"
          CreatePrivateHostedZone: "{{ dns_records.create_hosted_zone_bool }}"
          AemEnvS3BucketName: "{{ s3.data_bucket_name }}"
          PrivateHostedZoneName: "{{ dns_records.route53_hosted_zone_name }}"
          VPCId: "{{ network_exports.VPCId }}"
          VPCRegion: "{{ aws.region }}"
      tags:
        - create
